[build]
  command = "npm run build"
  publish = ".next"

[functions]
  # Increase function timeout for image processing
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]

[[plugins]]
  package = "@netlify/plugin-nextjs"